In [1]:
#1.Create a ID array
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [2]:
#2.accessing elements from the array
arr1[2]

3

In [5]:
#change an element from the array
arr1[2]=5
arr1

array([1, 2, 5])

In [6]:
arr1

array([1, 2, 5])

In [8]:
#3.Craete a 2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
#Check the shape of array
print("The shape is 2rows and 3 columns:",arr2.shape)

The shape is 2rows and 3 columns: (2, 3)


In [10]:
#4.accessing elements from the array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [11]:
#5.Array of type string
arr3=np.array(['India','China','USA','Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [12]:
arr3[1]

'China'

In [14]:
#6.Array of evenly spaced values within a specified interval
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [40]:
#Array of evenly spaced number in a specified interval
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [37]:
#7.Array of random values between 0 and 1 in  a given shape
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.46084544 0.01450917 0.99351333 0.8594263  0.24042968 0.10569779
 0.05427712 0.66157294 0.49099113 0.07859091]


[[0.66851544 0.92511764 0.78177692 0.49850083]
 [0.22357732 0.83892239 0.67774502 0.63511526]
 [0.00704222 0.21978196 0.86761621 0.32226917]]


In [23]:
#8.Array of constatnt values in a given shape
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [18]:
#9.Create an  array by repetition
#repeat each element of an array by a specified number of times
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [41]:
#10.Create and identity matrix
identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#11.create a 5*5 2D array for random numbers between 0 and 1
arr=np.random.rand(5,5)
print(arr)

[[0.85804427 0.5933133  0.71616469 0.30806975 0.44075926]
 [0.50152149 0.47975657 0.32041065 0.13743609 0.07229274]
 [0.63807253 0.22397221 0.34642842 0.92838604 0.88184366]
 [0.24037926 0.02022803 0.07651015 0.2432651  0.15606834]
 [0.99655209 0.84609227 0.01295406 0.19180362 0.73088381]]


In [21]:
#12.Sum an array along the column
print(np.sum(arr,axis=0))

[3.23456963 2.16336238 1.47246796 1.80896059 2.28184781]


In [22]:
#13.Sum an array along the row
print(np.sum(arr,axis=1))

[2.91635127 1.51141753 3.01870286 0.73645087 2.77828585]


In [25]:
#14.Calculate the mean,median,sd, and variance
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.4384483351031204
0.3464284208595433
0.30577445977586587
0.09349802025122261


In [26]:
#15.Sort an array along the row using the sort() function
arr=np.random.rand(5,5)
print(arr)

[[0.09369889 0.81083064 0.23206698 0.36202548 0.45992425]
 [0.79907649 0.8179482  0.26314388 0.27934154 0.34107854]
 [0.41989957 0.29794014 0.30081741 0.77629029 0.63402219]
 [0.78093156 0.54241978 0.23237162 0.03418693 0.53163413]
 [0.48476973 0.76525125 0.19864892 0.39668777 0.57801333]]


In [27]:
#sorting along the row
print(np.sort(arr,axis=1))

[[0.09369889 0.23206698 0.36202548 0.45992425 0.81083064]
 [0.26314388 0.27934154 0.34107854 0.79907649 0.8179482 ]
 [0.29794014 0.30081741 0.41989957 0.63402219 0.77629029]
 [0.03418693 0.23237162 0.53163413 0.54241978 0.78093156]
 [0.19864892 0.39668777 0.48476973 0.57801333 0.76525125]]


In [28]:
#16.Append elements to an array using the appand() fuction
arr=np.array([4,5,6,7])

In [29]:
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [30]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [31]:
#17.Delete mutiple elements in an array
arr2=np.array([4,5,6,7,8,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  8  9 10 11]


[ 4  6  7  9 10 11]


In [32]:
#18.Combine and split an array
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])


In [35]:
#Combine the array items by column
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [34]:
#combine array items by row
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
